/**
 * Initial Mock AMC Contracts Dataset (3.3.6 Warranty & AMC)
 * Maps SAMC / CAMC contracts to confirmed Order Fulfilments & PI records.
 */
export const initialMockAMCContracts = [
  {
    id: 'AMC-2026-001',
    contractId: 'AMC-2026-001',
    orderFulfilmentId: 'FUL-2026-003',
    piNumber: 'PI-2026-001-V1',
    client: 'Fortis Healthcare Centre',
    contactPerson: 'Dr. Ananya Verma',
    mobile: '9811223344',
    email: 'purchase@fortishealthcare.com',
    territory: 'Bengaluru, Karnataka',
    productSummary: 'GE Voluson E8 Expert Ultrasound Machine',
    productQty: 1,
    amcType: 'SAMC (Support AMC)',
    nature: 'Mandatory support only',
    startDate: '2025-05-11',
    endDate: '2026-05-10',
    period: '1 Year',
    basePrice: 135000,
    discount: 8000,
    gstPercent: 18,
    totalAmountCycle: 150000,
    totalAmount: 150000,
    alertBeforeDays: '30 Days',
    status: 'Pending Renewal',
    alertStatus: '30-Day Alert',
    notes: 'Warranty ended 2025-05-10. Auto-triggered SAMC contract due for annual renewal.'
  },
  {
    id: 'AMC-2026-002',
    contractId: 'AMC-2026-002',
    orderFulfilmentId: 'FUL-2026-001',
    piNumber: 'PI-2026-003-V1',
    client: 'KMCH Specialty Hospital',
    contactPerson: 'Dr. Subramanian',
    mobile: '9842155667',
    email: 'purchasing@kmch.org',
    territory: 'Coimbatore, Tamil Nadu',
    productSummary: 'Sonoscape X5 Portable Ultrasound System (Qty: 2)',
    productQty: 2,
    amcType: 'CAMC (Comprehensive AMC)',
    nature: 'Optional upgrade (Support + Software Upgrades)',
    startDate: '2026-08-28',
    endDate: '2028-08-27',
    period: '2 Years',
    basePrice: 320000,
    discount: 15000,
    gstPercent: 18,
    totalAmountCycle: 360000,
    totalAmount: 360000,
    alertBeforeDays: '60 Days',
    status: 'Active',
    alertStatus: 'Normal',
    notes: 'Upgraded to Comprehensive AMC with software version 4.2 upgrades included.'
  },
  {
    id: 'AMC-2026-003',
    contractId: 'AMC-2026-003',
    orderFulfilmentId: 'FUL-2026-002',
    piNumber: 'PI-2026-002-V1',
    client: 'Apollo Specialty Hospital',
    contactPerson: 'Dr. Ramesh Kumar',
    mobile: '9840012345',
    email: 'procurement@apollohospitals.com',
    territory: 'Chennai, Tamil Nadu',
    productSummary: 'Mindray DC-70 Ultrasound Machine',
    productQty: 1,
    amcType: 'SAMC (Support AMC)',
    nature: 'Mandatory support only',
    startDate: '2026-08-20',
    endDate: '2027-08-19',
    period: '1 Year',
    basePrice: 160000,
    discount: 7458,
    gstPercent: 18,
    totalAmountCycle: 180000,
    totalAmount: 180000,
    alertBeforeDays: '30 Days',
    status: 'Active',
    alertStatus: 'Normal',
    notes: 'Standard support contract active.'
  },
  {
    id: 'AMC-2026-004',
    contractId: 'AMC-2026-004',
    orderFulfilmentId: 'FUL-2026-004',
    piNumber: 'PI-2026-004-V1',
    client: 'Manipal Multi-Specialty Hospital',
    contactPerson: 'Dr. Vikram Seth',
    mobile: '9880011223',
    email: 'biomedical@manipal.edu',
    territory: 'Bengaluru, Karnataka',
    productSummary: 'Samsung HS50 Ultrasound Scanner',
    productQty: 1,
    amcType: 'SAMC (Support AMC)',
    nature: 'Mandatory support only',
    startDate: '2024-03-01',
    endDate: '2025-02-28',
    period: '1 Year',
    basePrice: 105000,
    discount: 3305,
    gstPercent: 18,
    totalAmountCycle: 120000,
    totalAmount: 120000,
    alertBeforeDays: '30 Days',
    status: 'Lapsed',
    alertStatus: 'Expired',
    notes: 'Contract expired without payment. Non-payment lapsed support coverage.'
  }
];
