/**
 * Mock Data for Subscription Orders (BR-ORD-016 & Rule 3.3.7)
 * Support is bundled directly into the subscription fee.
 */
export const initialMockSubscriptions = [
  {
    id: 'SUB-2026-001',
    subscriptionId: 'SUB-2026-001',
    orderFulfilmentId: 'FUL-2026-002',
    piNumber: 'PI-2026-002-V1',
    client: 'Apollo Hospitals & Diagnostic Centre',
    contactPerson: 'Dr. Rajesh Kumar',
    mobile: '9845012345',
    email: 'purchase@apollo.com',
    territory: 'Chennai, Tamil Nadu',
    productSummary: 'Sonoscape P20 Expert Diagnostic Ultrasound System',
    productQty: 1,
    category: 'Diagnostic Ultrasound System',
    serialNumber: 'SN-P20-2026-4412',
    softwareVersion: 'v5.1.0-SUB',
    licenseKey: 'LIC-SUB-P20-8812-B',
    installationDate: '2025-01-15',
    warrantyMonths: 'Bundled in Subscription',
    warrantyEndDate: 'N/A (Bundled)',
    subscriptionType: 'Monthly',
    billingCycle: 'Monthly (1st of every month)',
    price: 45000,
    basePrice: 40000,
    discountPercent: 5,
    gstPercent: 18,
    startDate: '2025-01-16',
    nextBillingDate: '2026-06-16',
    status: 'Active',
    paymentStatus: 'Paid',
    notes: 'Subscription order with bundled remote & on-site support. AMC excluded per BR-ORD-016.'
  },
  {
    id: 'SUB-2026-002',
    subscriptionId: 'SUB-2026-002',
    orderFulfilmentId: 'FUL-2026-004',
    piNumber: 'PI-2026-004-V1',
    client: 'Manipal Super Specialty Hospital',
    contactPerson: 'Dr. Meera Nambiar',
    mobile: '9880112233',
    email: 'radiology@manipal.edu',
    territory: 'Bengaluru, Karnataka',
    productSummary: 'Mindray DC-70 Ultrasound Imaging System',
    productQty: 1,
    category: 'Ultrasound Imaging System',
    serialNumber: 'SN-DC70-2026-9901',
    softwareVersion: 'v3.8.2-ULT',
    licenseKey: 'LIC-SUB-DC70-9921-C',
    installationDate: '2025-03-01',
    warrantyMonths: 'Bundled in Subscription',
    warrantyEndDate: 'N/A (Bundled)',
    subscriptionType: 'Yearly',
    billingCycle: 'Yearly (1st March)',
    price: 480000,
    basePrice: 425000,
    discountPercent: 10,
    gstPercent: 18,
    startDate: '2025-03-02',
    nextBillingDate: '2026-03-01',
    status: 'Active',
    paymentStatus: 'Paid',
    notes: 'Yearly subscription deal with full Software & Hardware bundled support.'
  },
  {
    id: 'SUB-2026-003',
    subscriptionId: 'SUB-2026-003',
    orderFulfilmentId: 'FUL-2026-007',
    piNumber: 'PI-2026-007-V1',
    client: 'Care Multispecialty Clinic',
    contactPerson: 'Dr. Suresh Varma',
    mobile: '9765432109',
    email: 'contact@careclinic.in',
    territory: 'Hyderabad, Telangana',
    productSummary: 'Sonoscape E2 Portable Cardiac Ultrasound',
    productQty: 1,
    category: 'Cardiac Ultrasound',
    serialNumber: 'SN-E2-2026-1102',
    softwareVersion: 'v2.4.0-STD',
    licenseKey: 'LIC-SUB-E2-1102-D',
    installationDate: '2025-02-10',
    warrantyMonths: 'Bundled in Subscription',
    warrantyEndDate: 'N/A (Bundled)',
    subscriptionType: 'Half-Yearly',
    billingCycle: 'Half-Yearly (Every 6 Months)',
    price: 135000,
    basePrice: 120000,
    discountPercent: 5,
    gstPercent: 18,
    startDate: '2025-02-11',
    nextBillingDate: '2025-08-11',
    status: 'Pending',
    paymentStatus: 'Pending',
    notes: 'Half-yearly subscription cycle pending 2nd installment payment.'
  }
];
