/**
 * Initial Mock Order Fulfilment Register Dataset
 * Mapped to confirmed Proforma Invoice (PI) records.
 */
export const initialMockFulfilments = [
  {
    id: 'FUL-2026-001',
    fulfilmentId: 'FUL-2026-001',
    piId: 'PI-2026-003-V1',
    piNumber: 'PI-2026-003-V1',
    versionNumber: 1,
    leadId: 'LEAD-003',
    customerName: 'KMCH Specialty Hospital',
    contactPerson: 'Dr. Subramanian',
    mobile: '9842155667',
    email: 'purchasing@kmch.org',
    billingAddress: 'KMCH Hospital Road, Avinashi Road, Coimbatore, Tamil Nadu 641014',
    deliveryAddress: 'KMCH Diagnostic Wing, Floor 2, Avinashi Road, Coimbatore, Tamil Nadu 641014',
    productSummary: 'Sonoscape X5 Portable Ultrasound System (Qty: 2)',
    totalOrderValue: 11800000,
    fieldEmployee: 'Suresh Babu',
    kitStatus: 'In Progress',
    paymentStatus: 'Partial',
    paidAmount: 5000000,
    installationStatus: 'Pending',
    installationDate: '2026-08-28',
    warrantyMonths: 12,
    warrantyEndDate: '2027-08-28',
    overallStatus: 'Pending',
    createdDate: '2026-08-25',
    kits: [
      {
        productId: 1,
        productName: 'Sonoscape X5 Portable Ultrasound System',
        specifications: '3D/4D Imaging, Color Doppler, 2 Transducer Probes included',
        quantity: 2,
        unitPrice: 5000000,
        discount: 0,
        lineTotal: 10000000,
        kitDetails: 'Main Console Box + Transducer Probes + Power Cable + Trolley Cart',
        licenseRequired: 'Yes',
        licenseType: 'Permanent Software Key',
        licenseQuantity: 2,
        licenseKey: 'LIC-X5-9821-KMCH',
        licenseStartDate: '2026-08-26',
        licenseExpiryDate: '2027-08-26',
        licenseStatus: 'Generated',
        licenseRemarks: '1-Year standard warranty software license key active.'
      }
    ]
  },
  {
    id: 'FUL-2026-002',
    fulfilmentId: 'FUL-2026-002',
    piId: 'PI-2026-002-V1',
    piNumber: 'PI-2026-002-V1',
    versionNumber: 1,
    leadId: 'LEAD-002',
    customerName: 'Apollo Specialty Hospital',
    contactPerson: 'Dr. Ramesh Kumar',
    mobile: '9840012345',
    email: 'procurement@apollohospitals.com',
    billingAddress: 'Apollo Hospitals Campus, Greams Road, Thousand Lights, Chennai, Tamil Nadu 600006',
    deliveryAddress: 'Apollo Radiology Dept, Greams Road, Chennai, Tamil Nadu 600006',
    productSummary: 'Mindray DC-70 Ultrasound Machine (Qty: 1)',
    totalOrderValue: 4500000,
    fieldEmployee: 'Kavitha Rajan',
    kitStatus: 'Pending',
    paymentStatus: 'Paid',
    paidAmount: 4500000,
    installationStatus: 'Scheduled',
    installationDate: '2026-08-20',
    warrantyMonths: 24,
    warrantyEndDate: '2028-08-20',
    overallStatus: 'Pending',
    createdDate: '2026-08-20',
    kits: []
  },
  {
    id: 'FUL-2026-003',
    fulfilmentId: 'FUL-2026-003',
    piId: 'PI-2026-001-V1',
    piNumber: 'PI-2026-001-V1',
    versionNumber: 1,
    leadId: 'LEAD-001',
    customerName: 'Fortis Healthcare Centre',
    contactPerson: 'Dr. Ananya Verma',
    mobile: '9811223344',
    email: 'purchase@fortishealthcare.com',
    billingAddress: 'Fortis Hospital Tower, Bannerghatta Road, Bengaluru, Karnataka 560076',
    deliveryAddress: 'Fortis Hospital OT Complex, Bannerghatta Road, Bengaluru, Karnataka 560076',
    productSummary: 'GE Voluson E8 Expert Ultrasound Machine (Qty: 1)',
    totalOrderValue: 7500000,
    fieldEmployee: 'Sridevi Raghavan',
    kitStatus: 'Generated',
    paymentStatus: 'Paid',
    paidAmount: 7500000,
    installationStatus: 'Completed',
    installationDate: '2024-05-10',
    warrantyMonths: 12,
    warrantyEndDate: '2025-05-10',
    overallStatus: 'Fulfilled',
    createdDate: '2026-08-15',
    kits: []
  }
];
