/**
 * Initial Mock Order Cancellation Data according to Rule 3.3.8
 */
export const initialMockCancellations = [
  {
    id: 'CAN-2026-001',
    cancellationId: 'CAN-2026-001',
    orderFulfilmentId: 'FUL-2026-001',
    customerName: 'Apollo Hospitals & Diagnostic Centre',
    contactPerson: 'Dr. Rajesh Kumar',
    mobile: '9845012345',
    email: 'purchase@apollo.com',
    productName: 'Sonoscape P20 Expert Diagnostic Ultrasound System',
    productQty: 1,
    orderTotal: 450000,
    cancellationStage: 'Before Dispatch',
    refundTerms: '100% Refund (-₹2,500 Fee)',
    chargePercent: 0,
    processingFee: 2500,
    refundAmount: 447500,
    managerApprovalRequired: false,
    managerApproved: true,
    managerApprovalStatus: 'Auto-Approved',
    managerNotes: 'Cancellation requested prior to dispatch. Standard 100% refund applied minus processing fee.',
    status: 'Approved',
    paymentStatus: 'Complete',
    requestDate: '2026-08-20',
    reason: 'Budget reallocation at hospital unit.'
  },
  {
    id: 'CAN-2026-002',
    cancellationId: 'CAN-2026-002',
    orderFulfilmentId: 'FUL-2026-002',
    customerName: 'Fortis Multi-Specialty Hospital',
    contactPerson: 'Dr. Ananya Verma',
    mobile: '9811223344',
    email: 'purchase@fortis.com',
    productName: 'Sonoscape X5 Portable Ultrasound System',
    productQty: 1,
    orderTotal: 380000,
    cancellationStage: 'After Dispatch',
    refundTerms: '30% Cancellation Charge Applied',
    chargePercent: 30,
    processingFee: 0,
    refundAmount: 266000,
    managerApprovalRequired: false,
    managerApproved: true,
    managerApprovalStatus: 'Approved',
    managerNotes: 'Consignment in transit. 30% logistics & cancellation fee deducted.',
    status: 'Refund Processed',
    paymentStatus: 'In Progress',
    requestDate: '2026-08-22',
    reason: 'Client selected upgraded model.'
  },
  {
    id: 'CAN-2026-003',
    cancellationId: 'CAN-2026-003',
    orderFulfilmentId: 'FUL-2026-003',
    customerName: 'Manipal Heart & Vascular Institute',
    contactPerson: 'Dr. Suresh Mehta',
    mobile: '9733445566',
    email: 'biomed@manipal.org',
    productName: 'Sonoscape S22 High-End Color Doppler',
    productQty: 1,
    orderTotal: 620000,
    cancellationStage: 'After Installation',
    refundTerms: '20% Restocking Fee (Requires Manager Approval)',
    chargePercent: 20,
    processingFee: 0,
    refundAmount: 496000,
    managerApprovalRequired: true,
    managerApproved: false,
    managerApprovalStatus: 'Pending Manager Approval',
    managerNotes: 'Equipment installed. Requires Regional Sales Manager review for return approval.',
    status: 'Pending Manager Approval',
    paymentStatus: 'Pending',
    requestDate: '2026-08-26',
    reason: 'Site infrastructure mismatch after installation.'
  }
];
