/**
 * Initial Mock Service Ticket Data with Multiselect Support Engineers, SLA Pause Data,
 * 3-Tier Escalation Fields, Parts & Commercial Quotation matrix (>₹5,000 rule), and Sign-Off.
 */
export const initialMockTickets = [
  {
    id: 'TCK-2026-001',
    ticketId: 'TCK-2026-001',
    customerName: 'Apollo Hospitals & Diagnostic Centre',
    contactPerson: 'Dr. Rajesh Kumar',
    mobile: '9845012345',
    email: 'purchase@apollo.com',
    territory: 'Chennai, Tamil Nadu',
    productName: 'Sonoscape P20 Expert Diagnostic Ultrasound System',
    category: 'Ultrasound Diagnostic Scanner',
    serialNumber: 'SN-P20-2026-4412',
    channel: 'Portal',
    type: 'CAMC',
    priority: 'Critical',
    assignedEngineer: 'Rajesh Sharma',
    assignedCoordinator: 'Karthik Raja',
    supportEngineers: ['Rajesh Sharma', 'Suresh Reddy'],
    engineerContacts: [
      { name: 'Rajesh Sharma', mobile: '9840112233', email: 'rajesh.sharma@sonocare.com', experience: 8, isSenior: true },
      { name: 'Suresh Reddy', mobile: '9740556677', email: 'suresh.reddy@sonocare.com', experience: 10, isSenior: true }
    ],
    dateCreated: '2026-08-28 09:30',
    lastUpdated: '2026-08-29 11:25',
    workStartDateTime: '2026-08-28 10:00',
    calculatedWorkEndDateTime: '2026-08-28 18:00',
    enteredWorkEndDateTime: '2026-08-28 17:30',
    totalPausedMinutes: 0,
    pausedAt: null,
    isSlaViolated: false,
    status: 'Resolved',
    escalationLevel: 'Support',
    feedback: '5 Stars - Excellent',
    feedbackRating: 5,
    issueSummary: 'Scheduled bi-annual probe calibration and general maintenance check under CAMC.',
    resolutionNotes: 'Transducer probe calibrated successfully. Power supply voltage verified within 0.2% tolerance. Customer sign-off verified via OTP & Digital Signature.',
    customerOtpVerified: true,
    customerSignatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><text x="10" y="35" font-family="cursive" font-size="22" fill="%232E3192">Dr. Rajesh Kumar</text></svg>',
    partsList: [
      { id: 1, partName: 'OEM Probe HV Board Assembly', cost: 14500, isAmcCovered: true, quotationRequired: false, quotationStatus: 'Covered under AMC (₹0)' }
    ],
    requiresTeamLeadSupport: false,
    teamLeadName: '',
    teamLeadMobile: '',
    teamLeadEmail: '',
    requiresDeveloperSupport: false,
    developerCount: 0,
    developerList: []
  },
  {
    id: 'TCK-2026-002',
    ticketId: 'TCK-2026-002',
    customerName: 'Fortis Multi-Specialty Hospital',
    contactPerson: 'Dr. Ananya Verma',
    mobile: '9811223344',
    email: 'purchase@fortis.com',
    territory: 'Bengaluru, Karnataka',
    productName: 'Sonoscape X5 Portable Ultrasound System',
    category: 'Ultrasound Diagnostic Scanner',
    serialNumber: 'SN-X5-2026-8812',
    channel: 'Phone',
    type: 'SAMC',
    priority: 'High',
    assignedEngineer: 'Amit Patel',
    assignedCoordinator: 'Karthik Raja',
    supportEngineers: ['Amit Patel'],
    engineerContacts: [
      { name: 'Amit Patel', mobile: '9811223344', email: 'amit.patel@sonocare.com', experience: 6, isSenior: true }
    ],
    dateCreated: '2026-08-28 11:00',
    lastUpdated: '2026-08-29 11:20',
    workStartDateTime: '2026-08-28 12:00',
    calculatedWorkEndDateTime: '2026-08-31 15:00',
    enteredWorkEndDateTime: '2026-08-31 16:00',
    totalPausedMinutes: 120,
    pausedAt: '2026-08-28 14:00',
    isSlaViolated: false,
    status: 'Waiting for Customer/Parts',
    escalationLevel: 'Developer',
    feedback: 'Pending Feedback',
    feedbackRating: 0,
    issueSummary: 'Display panel flickers intermittently when Doppler mode is active.',
    resolutionNotes: 'Replacement display ribbon cable & HV module required. Quotation generated for approval.',
    customerOtpVerified: false,
    customerSignatureUrl: null,
    partsList: [
      { id: 1, partName: 'Display Ribbon Cable & Interface Controller', cost: 8500, isAmcCovered: false, quotationRequired: true, quotationStatus: 'Pending Quotation Approval' }
    ],
    requiresTeamLeadSupport: true,
    teamLeadName: 'Suresh Reddy (Lead)',
    teamLeadMobile: '9740556677',
    teamLeadEmail: 'suresh.reddy@sonocare.com',
    teamLeadCompletionDateTime: '2026-08-28 15:00',
    teamLeadRemarks: 'Reviewed display board assembly. Approved quotation generation for ₹8,500.',
    requiresDeveloperSupport: true,
    developerCount: 1,
    developerList: [
      { name: 'Rohan Deshmukh (Firmware Dev)', mobile: '9811002233', email: 'rohan.dev@sonocare.com', remarks: 'Patch v4.2.1 compiled', completedDateTime: '2026-08-28 16:30' }
    ]
  },
  {
    id: 'TCK-2026-003',
    ticketId: 'TCK-2026-003',
    customerName: 'Manipal Heart & Vascular Institute',
    contactPerson: 'Dr. Suresh Mehta',
    mobile: '9733445566',
    email: 'biomed@manipal.org',
    territory: 'Hyderabad, Telangana',
    productName: 'Sonoscape S22 High-End Color Doppler',
    category: 'Color Doppler Ultrasound',
    serialNumber: 'SN-S22-2026-9014',
    channel: 'Email',
    type: 'Subscription',
    priority: 'Medium',
    assignedEngineer: 'Vikram Singh',
    assignedCoordinator: 'Karthik Raja',
    supportEngineers: ['Vikram Singh'],
    engineerContacts: [
      { name: 'Vikram Singh', mobile: '9733114422', email: 'vikram.singh@sonocare.com', experience: 4, isSenior: false }
    ],
    dateCreated: '2026-08-29 09:00',
    lastUpdated: '2026-08-29 11:15',
    workStartDateTime: '2026-08-29 09:30',
    calculatedWorkEndDateTime: '2026-09-03 14:00',
    enteredWorkEndDateTime: '2026-09-03 14:00',
    totalPausedMinutes: 0,
    pausedAt: null,
    isSlaViolated: false,
    status: 'In Progress',
    escalationLevel: 'Support',
    feedback: 'Pending Feedback',
    feedbackRating: 0,
    issueSummary: 'DICOM export configuration assistance required for PACS integration under monthly subscription.',
    resolutionNotes: 'Remote support session active with hospital IT team.',
    customerOtpVerified: false,
    customerSignatureUrl: null,
    partsList: [],
    requiresTeamLeadSupport: false,
    teamLeadName: '',
    teamLeadMobile: '',
    teamLeadEmail: '',
    requiresDeveloperSupport: false,
    developerCount: 0,
    developerList: []
  },
  {
    id: 'TCK-2026-004',
    ticketId: 'TCK-2026-004',
    customerName: 'Max Super Specialty Hospital',
    contactPerson: 'Dr. Meera Nambiar',
    mobile: '9899112233',
    email: 'purchase@maxhealth.com',
    territory: 'Delhi NCR, New Delhi',
    productName: 'Sonoscape P20 Expert Diagnostic Ultrasound System',
    category: 'Ultrasound Diagnostic Scanner',
    serialNumber: 'SN-P20-2026-1109',
    channel: 'Portal',
    type: 'SAMC',
    priority: 'Critical',
    assignedEngineer: 'Anil Kapoor',
    assignedCoordinator: 'Karthik Raja',
    supportEngineers: ['Anil Kapoor'],
    engineerContacts: [
      { name: 'Anil Kapoor', mobile: '9899112233', email: 'anil.kapoor@sonocare.com', experience: 7, isSenior: true }
    ],
    dateCreated: '2026-08-27 10:00',
    lastUpdated: '2026-08-29 11:00',
    workStartDateTime: '2026-08-27 10:30',
    calculatedWorkEndDateTime: '2026-08-27 18:30',
    enteredWorkEndDateTime: '2026-08-27 18:00',
    totalPausedMinutes: 0,
    pausedAt: null,
    isSlaViolated: false,
    status: 'Closed',
    escalationLevel: 'Team Lead',
    feedback: '4 Stars - Good',
    feedbackRating: 4,
    issueSummary: 'Linear array probe sensitivity check and user training for cardiac preset under SAMC.',
    resolutionNotes: 'On-site training completed for department radiologists. Customer OTP and signature recorded.',
    customerOtpVerified: true,
    customerSignatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><text x="10" y="35" font-family="cursive" font-size="22" fill="%232E3192">Dr. Meera Nambiar</text></svg>',
    partsList: [
      { id: 1, partName: 'Probe Coupler Oil Solution', cost: 1200, isAmcCovered: false, quotationRequired: false, quotationStatus: 'Direct Billing (<= ₹5,000)' }
    ],
    requiresTeamLeadSupport: true,
    teamLeadName: 'Anil Kapoor (Lead)',
    teamLeadMobile: '9899112233',
    teamLeadEmail: 'anil.kapoor@sonocare.com',
    requiresDeveloperSupport: false,
    developerCount: 0,
    developerList: []
  }
];
