// Mock Dataset for Campaign Contacts
export const initialMockCampaignContacts = [
  {
    id: 1,
    contactId: 'CC-001',
    campaignId: 'CMP-001',
    contactName: 'Dr. Arunkumar V',
    customerType: 'Hospital',
    otherCustomerType: '',
    email: 'arunkumar.v@apollohospitals.com',
    mobile: '9840112233',
    institution: 'Apollo Speciality Hospital',
    speciality: 'Radiology',
    territory: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    pincode: '600006',
    address: 'Greams Road, Thousand Lights, Chennai'
  },
  {
    id: 2,
    contactId: 'CC-002',
    campaignId: 'CMP-001',
    contactName: 'Dr. Meenakshi Sundaram',
    customerType: 'Diagnostic Lab',
    otherCustomerType: '',
    email: 'meenakshi.s@medall.in',
    mobile: '9840223344',
    institution: 'Medall Healthcare & Diagnostics',
    speciality: 'Sonology',
    territory: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    pincode: '600018',
    address: 'Mylapore High Road, Chennai'
  },
  {
    id: 3,
    contactId: 'CC-003',
    campaignId: 'CMP-002',
    contactName: 'Dr. Senthil Nathan',
    customerType: 'Hospital',
    otherCustomerType: '',
    email: 'senthil.n@kmch.ac.in',
    mobile: '9842155667',
    institution: 'Kovai Medical Center and Hospital (KMCH)',
    speciality: 'Cardiology',
    territory: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    pincode: '641014',
    address: 'Avinashi Road, Civil Aerodrome Post, Coimbatore'
  },
  {
    id: 4,
    contactId: 'CC-004',
    campaignId: 'CMP-002',
    contactName: 'Dr. Kavitha Raman',
    customerType: 'Clinic',
    otherCustomerType: '',
    email: 'kavitha@ramandiagnostics.com',
    mobile: '9842266778',
    institution: 'Raman UltraSound & Echo Center',
    speciality: 'Obstetrics & Gynecology',
    territory: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    pincode: '641002',
    address: 'DB Road, RS Puram, Coimbatore'
  },
  {
    id: 5,
    contactId: 'CC-005',
    campaignId: 'CMP-003',
    contactName: 'Dr. Joseph Kurian',
    customerType: 'Hospital',
    otherCustomerType: '',
    email: 'joseph.kurian@asterhospital.com',
    mobile: '9895112244',
    institution: 'Aster Medcity',
    speciality: 'Cardiology',
    territory: 'Kerala',
    district: 'Ernakulam',
    city: 'Kochi',
    pincode: '682027',
    address: 'Kuttisahib Road, Cheranalloor, Kochi'
  },
  {
    id: 6,
    contactId: 'CC-006',
    campaignId: 'CMP-004',
    contactName: 'Dr. Ramesh Chandran',
    customerType: 'Hospital',
    otherCustomerType: '',
    email: 'ramesh.c@meenakshihospital.in',
    mobile: '9790188990',
    institution: 'Meenakshi Mission Hospital',
    speciality: 'Urology',
    territory: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Madurai',
    pincode: '625107',
    address: 'Lake Area, Melur Road, Madurai'
  },
  {
    id: 7,
    contactId: 'CC-007',
    campaignId: 'CMP-005',
    contactName: 'Dr. Sunita Deshmukh',
    customerType: 'Other',
    otherCustomerType: 'Research Institute',
    email: 'sunita.d@iisc.ac.in',
    mobile: '9880177665',
    institution: 'IISc Biomedical Imaging Center',
    speciality: 'Biomedical Ultrasound',
    territory: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    pincode: '560012',
    address: 'CV Raman Road, Bengaluru'
  }
];
