export const initialMockProducts = [
  {
    id: 1,
    productId: 'PRD-1001',
    category: 'Machinery & Equipment',
    productName: 'Heavy CNC Milling Center 5000',
    specification: '5-Axis Precision Milling with 12000 RPM Spindle',
    modelNo: 'CNC-5000X',
    hsnCode: '8459',
    purchasePrice: 450000.0,
    gstPercent: 18,
    subscriptionMonthlyPrice: 45000.0,
    subscriptionQuarterlyPrice: 125000.0,
    subscriptionHalfYearlyPrice: 240000.0,
    subscriptionYearlyPrice: 450000.0,
    cancellationBeforeDispatch: 5.0,
    cancellationAfterDispatch: 15.0,
    cancellationAfterInstallation: 25.0,
    kitRequirement: 'Yes',
    status: 'Active',
    description: 'Industrial heavy machinery CNC milling center for automated manufacturing and high-precision metal tooling.'
  },
  {
    id: 2,
    productId: 'PRD-1002',
    category: 'Tooling & Accessories',
    productName: 'Precision CNC Collet Assembly Kit',
    specification: 'ER32 Spring Collet Set (18 Pcs)',
    modelNo: 'COLLET-ER32',
    hsnCode: '8466',
    purchasePrice: 85000.0,
    gstPercent: 18,
    subscriptionMonthlyPrice: 8500.0,
    subscriptionQuarterlyPrice: 24000.0,
    subscriptionHalfYearlyPrice: 45000.0,
    subscriptionYearlyPrice: 85000.0,
    cancellationBeforeDispatch: 2.0,
    cancellationAfterDispatch: 10.0,
    cancellationAfterInstallation: 15.0,
    kitRequirement: 'Yes',
    status: 'Active',
    description: 'High-precision workholding fixtures and CNC collet assemblies for toolholders.'
  },
  {
    id: 3,
    productId: 'PRD-1003',
    category: 'Electrical & Automation',
    productName: 'Industrial PLC Servo Controller Unit',
    specification: '32-Channel Digital I/O Modbus TCP/IP',
    modelNo: 'PLC-SERVO-32',
    hsnCode: '8537',
    purchasePrice: 320000.0,
    gstPercent: 18,
    subscriptionMonthlyPrice: 32000.0,
    subscriptionQuarterlyPrice: 90000.0,
    subscriptionHalfYearlyPrice: 170000.0,
    subscriptionYearlyPrice: 320000.0,
    cancellationBeforeDispatch: 5.0,
    cancellationAfterDispatch: 20.0,
    cancellationAfterInstallation: 30.0,
    kitRequirement: 'No',
    status: 'Active',
    description: 'Control panels, AC drives, and servo motor controllers with automation sensors.'
  },
  {
    id: 4,
    productId: 'PRD-1004',
    category: 'Medical & Diagnostic Scanners',
    productName: 'Sonocare HD Cardiac Probe Transducer',
    specification: 'Phased Array 1-5 MHz Diagnostic Cardiac Probe',
    modelNo: 'SONO-CP15',
    hsnCode: '9018',
    purchasePrice: 1250000.0,
    gstPercent: 12,
    subscriptionMonthlyPrice: 125000.0,
    subscriptionQuarterlyPrice: 350000.0,
    subscriptionHalfYearlyPrice: 650000.0,
    subscriptionYearlyPrice: 1200000.0,
    cancellationBeforeDispatch: 3.0,
    cancellationAfterDispatch: 12.0,
    cancellationAfterInstallation: 20.0,
    kitRequirement: 'Yes',
    status: 'Inactive',
    description: 'Diagnostic ultrasound transducer probe for cardiac and abdominal healthcare diagnostics.'
  }
];
